### PR TITLE
Form API

### PR DESCRIPTION
**Pull request by Sly-Zipy**
That Simple Forms is Wrong So I Change to 
use jojoe77777\FormAPI;

### CODE REVIEW

**Comment by MHIGists** [comment]
Thanks for the PR will check tonight and merge after testing

**Comment by Sly-Zipy** [comment]
Okay If You Done Fix That Can you Tell me? Because i want try that Plugin

Pada tanggal Sen, 4 Mei 2020 17.44, M.Ivanov <notifications@github.com>
menulis:

**Comment by MHIGists** [comment]
Hello just checked last dev build and forms are just fine are you experiencing problems running it?
Also keep in mind that the plugin isn't finished and is not ready for production servers.

**Comment by MHIGists** [comment]
Open an issue if you still have the problem

**Pull request closed without merging**
